# Generated by Django 5.2.10 on 2026-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='hora_fin_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='intentos_llamada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turno',
            name='ventanilla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'En Espera'), ('LLAMADO', 'Llamando por Altavoz'), ('EN_ATENCION', 'En Atención en Ventanilla'), ('FINALIZADO', 'Finalizado'), ('NO_SHOW', 'No se presentó')], default='ESPERA', max_length=20),
        ),
    ]
